#!/usr/bin/env python3
"""
ABot-PhysWorld DPO (Direct Preference Optimization) LoRA Training Script

Train a LoRA adapter on the DiT backbone using DPO to align video generation
with physical plausibility preferences. Given pairs of winner/loser videos,
the model learns to generate videos that better match physical laws.

This script implements:
    - DPO loss with per-sample MSE (supports batch_size > 1)
    - LoRA fine-tuning via PEFT (reference model via disable_adapter)
    - PyTorch Lightning training loop
    - Warmup steps for training stability

The training data is pre-processed .pth cache files generated by preprocess_dpo.py,
containing VAE-encoded latents, T5/CLIP features for winner/loser video pairs.

Features:
    - Per-sample MSE loss (no batch_size=1 restriction)
    - Reference model via PEFT disable_adapter (no extra memory)
    - Configurable beta_dpo, lora_rank, lora_alpha
    - Gradient checkpointing support
    - Multi-GPU training via PyTorch Lightning

Usage:
    # Train with pre-processed cache
    python train_dpo.py \\
        --cache_dir /path/to/dpo_cache \\
        --dit_checkpoint /path/to/dit_checkpoint.safetensors \\
        --output_path ./outputs/dpo_training

    # Or use the shell wrapper
    bash run_train_dpo.sh

Requirements:
    - DiffSynth-Studio (bundled in ../inference/diffsynth/)
    - lightning >= 2.0.0
    - peft >= 0.4.0
    - Pre-processed DPO cache from preprocess_dpo.py
"""

import os
import sys
import argparse
import torch
import torch.nn.functional as F
import lightning as pl
from pathlib import Path

# Add inference directory to path for importing bundled diffsynth module
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'inference'))
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")

from diffsynth import load_state_dict
from diffsynth.pipelines.wan_video_new import WanVideoPipeline, ModelConfig
from diffsynth.trainers.utils import DiffusionTrainingModule
from peft import LoraConfig, get_peft_model


class DPOTensorDataset(torch.utils.data.Dataset):
    """Dataset for loading DPO pre-processed cache (.pth files).

    Each .pth file contains winner/loser pairs with:
        - latents_w, latents_l: VAE-encoded video latents
        - y_w, y_l: image conditioning features
        - clip_fea_w, clip_fea_l: CLIP features
        - prompt_emb: dict with 'context' key (T5 text embeddings)
    """

    def __init__(self, cache_dir, steps_per_epoch):
        self.cache_dir = Path(cache_dir)
        self.paths = sorted(self.cache_dir.glob("*.pth"))
        assert len(self.paths) > 0, "No .pth files found in %s" % cache_dir
        self.steps_per_epoch = steps_per_epoch
        print("[DPO] Cache loaded: %d pairs, steps_per_epoch=%d" % (len(self.paths), steps_per_epoch))

    def __getitem__(self, index):
        i = (index + torch.randint(0, len(self.paths), (1,)).item()) % len(self.paths)
        data = torch.load(self.paths[i], weights_only=True, map_location="cpu")
        return data

    def __len__(self):
        return self.steps_per_epoch


class DPOPhysicsLightningModule(DiffusionTrainingModule, pl.LightningModule):
    """DPO training module using LoRA on DiT backbone.

    The reference model is implemented via PEFT's disable_adapter mechanism,
    which temporarily disables the LoRA adapter to compute reference predictions
    without requiring a separate copy of the model.

    Key design decisions:
        - Per-sample MSE: loss is computed per sample then averaged over batch,
          ensuring correct DPO gradients for batch_size > 1
        - Per-sample timestep: each sample in the batch gets its own timestep
        - Warmup: first N steps have zero loss for training stability
    """

    def __init__(
        self,
        model_id_with_origin_paths,
        dit_checkpoint,
        learning_rate=1e-6,
        lora_rank=64,
        lora_alpha=64,
        lora_target_modules="q,k,v,o,ffn.0,ffn.2",
        beta_dpo=5000,
        use_gradient_checkpointing=True,
        warmup_steps=10,
        skip_vae=False,
        skip_text_encoder=False,
        skip_image_encoder=False,
    ):
        DiffusionTrainingModule.__init__(self)
        pl.LightningModule.__init__(self)
        self.learning_rate = learning_rate
        self.beta_dpo = beta_dpo
        self.use_gradient_checkpointing = use_gradient_checkpointing
        self.warmup_steps = warmup_steps
        self.trained_steps = 0

        # Parse model configs
        model_configs = self.parse_model_configs(None, model_id_with_origin_paths)

        # Skip models when using cache mode (saves VRAM)
        if skip_vae or skip_text_encoder or skip_image_encoder:
            filtered_configs = []
            skipped_models = []
            for config in model_configs:
                pattern = getattr(config, "origin_file_pattern", "") or ""
                if skip_vae and "VAE" in pattern:
                    skipped_models.append("VAE (%s)" % pattern)
                    continue
                if skip_text_encoder and ("t5" in pattern.lower() or "text" in pattern.lower()):
                    skipped_models.append("TextEncoder (%s)" % pattern)
                    continue
                if skip_image_encoder and ("clip" in pattern.lower() or "image" in pattern.lower()):
                    skipped_models.append("ImageEncoder (%s)" % pattern)
                    continue
                filtered_configs.append(config)
            if skipped_models:
                print("=" * 60)
                print("[DPO cache mode] Skipping model loading to save VRAM:")
                for m in skipped_models:
                    print("   - %s" % m)
                print("=" * 60)
            model_configs = filtered_configs

        self.pipe = WanVideoPipeline.from_pretrained(
            torch_dtype=torch.bfloat16,
            device="cpu",
            model_configs=model_configs,
        )
        self.pipe.scheduler.set_timesteps(1000, training=True)
        self.pipe.requires_grad_(False)
        self.pipe.eval()

        # Load SFT checkpoint into DiT
        if dit_checkpoint and os.path.isfile(dit_checkpoint):
            ckpt = load_state_dict(dit_checkpoint)
            missing, unexpected = self.pipe.dit.load_state_dict(ckpt, strict=False)
            print("[DPO] Loaded DiT from %s, missing=%d, unexpected=%d"
                  % (dit_checkpoint, len(missing), len(unexpected)))
        else:
            print("[WARNING] No DiT checkpoint at %s" % dit_checkpoint)

        # Set DiT to training mode
        if hasattr(self.pipe, "denoising_model") and self.pipe.denoising_model() is not None:
            self.pipe.denoising_model().train()
        else:
            self.pipe.dit.train()

        # Apply LoRA via PEFT (enables disable_adapter for reference model)
        lora_config = LoraConfig(
            r=lora_rank,
            lora_alpha=lora_alpha,
            init_lora_weights="gaussian",
            target_modules=[m.strip() for m in lora_target_modules.split(",")],
        )
        self.pipe.dit = get_peft_model(self.pipe.dit, lora_config, adapter_name="learner")

    def training_step(self, batch, batch_idx):
        self.trained_steps += 1
        device = self.device
        dtype = self.pipe.torch_dtype

        # Load cached data
        latents_w = batch["latents_w"].to(device=device, dtype=dtype)
        latents_l = batch["latents_l"].to(device=device, dtype=dtype)
        # Cache stores y as [1, 20, 21, 60, 104]; DataLoader stacks to 6D; model needs 5D
        y_w = batch["y_w"].to(device=device, dtype=dtype).squeeze(0)
        y_l = batch["y_l"].to(device=device, dtype=dtype).squeeze(0)
        clip_fea_w = batch["clip_fea_w"].to(device=device, dtype=dtype).squeeze(0)
        clip_fea_l = batch["clip_fea_l"].to(device=device, dtype=dtype).squeeze(0)

        prompt_emb = batch["prompt_emb"]
        context = prompt_emb["context"].to(device=device, dtype=dtype).squeeze(0)

        bsz = latents_w.shape[0]

        # Same noise for winner and loser (DPO controlled variable)
        noise = torch.randn_like(latents_w)

        # Per-sample timestep sampling: each sample gets its own timestep
        timestep_ids = torch.randint(
            0, self.pipe.scheduler.num_train_timesteps, (bsz,), device="cpu"
        )
        timestep = self.pipe.scheduler.timesteps[timestep_ids].to(device=device, dtype=dtype)

        noisy_w = self.pipe.scheduler.add_noise(latents_w, noise, timestep)
        noisy_l = self.pipe.scheduler.add_noise(latents_l, noise, timestep)
        target_w = self.pipe.scheduler.training_target(latents_w, noise, timestep)
        target_l = self.pipe.scheduler.training_target(latents_l, noise, timestep)

        models = {n: getattr(self.pipe, n) for n in self.pipe.in_iteration_models}

        def _inputs(latents_noisy, y, clip_fea):
            return {
                "latents": latents_noisy,
                "timestep": timestep,
                "context": context,
                "clip_feature": clip_fea,
                "y": y,
                "use_gradient_checkpointing": self.use_gradient_checkpointing,
                "use_gradient_checkpointing_offload": False,
                "cfg_merge": False,
            }

        with torch.amp.autocast(device_type="cuda", dtype=torch.bfloat16):
            # Current policy predictions (LoRA enabled)
            pred_w = self.pipe.model_fn(**models, **_inputs(noisy_w, y_w, clip_fea_w))
            pred_l = self.pipe.model_fn(**models, **_inputs(noisy_l, y_l, clip_fea_l))

            # Reference model predictions (LoRA disabled)
            with torch.no_grad():
                with self.pipe.dit.disable_adapter():
                    ref_w = self.pipe.model_fn(**models, **_inputs(noisy_w, y_w, clip_fea_w))
                    ref_l = self.pipe.model_fn(**models, **_inputs(noisy_l, y_l, clip_fea_l))

                # Per-sample MSE for reference (no gradient needed)
                # Reduce over all dims except batch: mean(dim=[1, 2, ...])
                reduce_dims = list(range(1, ref_w.ndim))
                ref_mse_w = (ref_w.float() - target_w.float()).pow(2).mean(dim=reduce_dims)
                ref_mse_l = (ref_l.float() - target_l.float()).pow(2).mean(dim=reduce_dims)
                del ref_w, ref_l  # Free memory early (not needed for backward)

            # Per-sample MSE for current policy
            reduce_dims = list(range(1, pred_w.ndim))
            mse_w = (pred_w.float() - target_w.float()).pow(2).mean(dim=reduce_dims)
            mse_l = (pred_l.float() - target_l.float()).pow(2).mean(dim=reduce_dims)

            # DPO loss: -log(sigmoid(-beta/2 * ((mse_w - mse_l) - (ref_mse_w - ref_mse_l))))
            ref_diff = ref_mse_w - ref_mse_l
            model_diff = mse_w - mse_l
            scale = -0.5 * self.beta_dpo
            inside = scale * (model_diff - ref_diff)
            implicit_acc = (inside > 0).float().mean()
            loss = -F.logsigmoid(inside).mean()

            self.log("train_loss", loss, prog_bar=True)
            self.log("implicit_acc", implicit_acc, prog_bar=True)
            self.log("avg_model_mse", (mse_w + mse_l).mean().item() * 0.5, prog_bar=True)
            self.log("avg_ref_mse", (ref_mse_w + ref_mse_l).mean().item() * 0.5, prog_bar=True)

            if self.trainer.global_rank == 0:
                avg_m = (mse_w + mse_l).mean().item() * 0.5
                avg_r = (ref_mse_w + ref_mse_l).mean().item() * 0.5
                print(
                    "step %d loss=%.6f implicit_acc=%.4f avg_model_mse=%.6f avg_ref_mse=%.6f"
                    % (self.trained_steps, loss.item(), implicit_acc.item(), avg_m, avg_r),
                    flush=True,
                )

        if self.trained_steps <= self.warmup_steps:
            return loss * 0.0
        return loss

    def configure_optimizers(self):
        params = [p for p in self.pipe.dit.parameters() if p.requires_grad]
        return torch.optim.AdamW(params, lr=self.learning_rate)

    def on_save_checkpoint(self, ckpt):
        if self.trainer.global_rank != 0:
            return
        ckpt.clear()
        names = {n for n, p in self.pipe.dit.named_parameters() if p.requires_grad}
        state = self.pipe.dit.state_dict()
        for n in names:
            if n in state:
                ckpt[n] = state[n]


def parse_args():
    p = argparse.ArgumentParser(description="ABot-PhysWorld DPO LoRA Training")
    p.add_argument("--task", type=str, default="train", choices=["train"])
    p.add_argument("--cache_dir", type=str, required=True,
                   help="DPO .pth cache directory from preprocess_dpo.py")
    p.add_argument("--output_path", type=str, default="./outputs/dpo_training",
                   help="Output directory for checkpoints and logs")
    p.add_argument("--model_id_with_origin_paths", type=str,
                   default="Wan-AI/Wan2.1-I2V-14B-480P:diffusion_pytorch_model*.safetensors,"
                           "Wan-AI/Wan2.1-I2V-14B-480P:models_t5_umt5-xxl-enc-bf16.pth,"
                           "Wan-AI/Wan2.1-I2V-14B-480P:Wan2.1_VAE.pth,"
                           "Wan-AI/Wan2.1-I2V-14B-480P:models_clip_open-clip-xlm-roberta-large-vit-huge-14.pth")
    p.add_argument("--dit_checkpoint", type=str, required=True,
                   help="SFT DiT checkpoint path (e.g., dit_checkpoint.safetensors)")
    p.add_argument("--steps_per_epoch", type=int, default=500,
                   help="Number of training steps per epoch")
    p.add_argument("--max_epochs", type=int, default=100,
                   help="Maximum training epochs")
    p.add_argument("--learning_rate", type=float, default=1e-6)
    p.add_argument("--lora_rank", type=int, default=64)
    p.add_argument("--lora_alpha", type=float, default=64.0)
    p.add_argument("--lora_target_modules", type=str, default="q,k,v,o,ffn.0,ffn.2",
                   help="Comma-separated list of LoRA target modules")
    p.add_argument("--beta_dpo", type=float, default=5000.0,
                   help="DPO beta parameter (controls preference strength)")
    p.add_argument("--use_gradient_checkpointing", action="store_true",
                   help="Enable gradient checkpointing to save VRAM")
    p.add_argument("--warmup_steps", type=int, default=10,
                   help="Number of warmup steps (zero loss)")
    p.add_argument("--skip_vae", action="store_true",
                   help="Skip loading VAE when using cache (saves VRAM)")
    p.add_argument("--skip_text_encoder", action="store_true",
                   help="Skip loading T5 text encoder when using cache")
    p.add_argument("--skip_image_encoder", action="store_true",
                   help="Skip loading CLIP image encoder when using cache")
    p.add_argument("--batch_size", type=int, default=1,
                   help="Per-GPU batch size (per-sample MSE supports >1)")
    p.add_argument("--num_workers", type=int, default=4,
                   help="DataLoader worker count")
    p.add_argument("--accumulate_grad_batches", type=int, default=1,
                   help="Gradient accumulation steps")
    p.add_argument("--num_nodes", type=int, default=None,
                   help="Number of nodes (auto-detected from WORLD_SIZE if not set)")
    return p.parse_args()


def train(args):
    dataset = DPOTensorDataset(args.cache_dir, steps_per_epoch=args.steps_per_epoch)
    loader = torch.utils.data.DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
    )
    model = DPOPhysicsLightningModule(
        model_id_with_origin_paths=args.model_id_with_origin_paths,
        dit_checkpoint=args.dit_checkpoint,
        learning_rate=args.learning_rate,
        lora_rank=args.lora_rank,
        lora_alpha=args.lora_alpha,
        lora_target_modules=args.lora_target_modules,
        beta_dpo=args.beta_dpo,
        use_gradient_checkpointing=args.use_gradient_checkpointing,
        warmup_steps=args.warmup_steps,
        skip_vae=args.skip_vae,
        skip_text_encoder=args.skip_text_encoder,
        skip_image_encoder=args.skip_image_encoder,
    )

    if args.num_nodes is not None:
        num_nodes = args.num_nodes
    else:
        world_size = int(os.environ.get("WORLD_SIZE", 1))
        local_world_size = int(os.environ.get("LOCAL_WORLD_SIZE", 1))
        num_nodes = max(1, world_size // local_world_size)

    # Auto-detect accelerator (supports CUDA, ROCm, MPS)
    if torch.cuda.is_available():
        accelerator = "gpu"
    else:
        _has_rocm = hasattr(torch.version, "hip") and torch.version.hip is not None
        accelerator = "gpu" if _has_rocm else "auto"

    trainer = pl.Trainer(
        max_epochs=args.max_epochs,
        accelerator=accelerator,
        devices="auto",
        num_nodes=num_nodes,
        default_root_dir=args.output_path,
        accumulate_grad_batches=args.accumulate_grad_batches,
        callbacks=[pl.pytorch.callbacks.ModelCheckpoint(save_top_k=-1)],
    )
    trainer.fit(model, loader)


if __name__ == "__main__":
    args = parse_args()
    if args.task == "train":
        train(args)
